# Generated by Django 6.0.7 on 2026-08-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('CEDAR ROOM', 'Cozy Forest Facing Room'), ('KAIDE SUIT', 'Spacious Suite with Balcony'), ('PINE VILLA', 'Private Villa Surrounded By Trees'), ('MOSS RESIDENCE', 'Premium Family Residence'), ('SUMMIT SUITE', 'Best Mountain Views'), ('CANOPY VILLA', 'elevated Forest Retreat'), ('SORA SUITE', 'Sky View Retreat')], default='CEDAR ROOM', max_length=20),
        ),
    ]
